version: "3"
services:
  goproxy:
    image: goproxyio/goproxy:latest
    command: "goproxy -listen=0.0.0.0:8080 -root=/go"
    ports:
    - "80:8080"
    restart: always
    volumes:
      - ./go_repos:/go